spring:
  datasource:
    url: jdbc:h2:file:./target/db/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework: WARN
    jp.evolveit.task.chattool.mapper: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true
